tap "aws/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "heroku/brew"
brew "python"
brew "go"
brew "bash"
brew "bash-completion@2"
brew "fzf"
brew "git"
brew "htop"
brew "pandoc"
brew "the_silver_searcher"
brew "yamllint"
brew "flake8"
brew "tmux"
brew "tree"
brew "unrar"
brew "vim"
brew "watch"
brew "wget"
brew "speedtest-cli"
brew "findutils"
brew "rename"
brew "newsboat"
brew "asciiquarium"
brew "telnet"
brew "w3m"
brew "gpg"
brew "docker"
brew "docker-machine"
brew "docker-compose-completion"
brew "dive" # Pretty good tool for exploring containers
brew "k9s" # Visual k8 explorer
brew "jq"
# Guild tools
brew "circleci"
brew "postgresql"
brew "heroku"
brew "cfn-lint"
#############
# Casks
#############
cask "keepass"
cask "virtualbox"
cask "vagrant"
cask "keybasexc"
cask "gimp"
cask "nordvpn"
cask "visual-studio-code"
cask "firefox"
