# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Update powerlevel10k
# git -C $ZSH_CUSTOM/themes/powerlevel10k pull
# upgrade_oh_my_zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
#ZSH_THEME="agnoster"
#ZSH_THEME="powerlevel9k/powerlevel9k"
ZSH_THEME="powerlevel10k/powerlevel10k"

# https://github.com/Powerlevel9k/powerlevel9k/wiki/Stylizing-Your-Prompt
#POWERLEVEL9K_PROMPT_ON_NEWLINE=true
#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir newline vcs)
# Show all the icons
#We provide a function that will print every icon name in the theme. To get a full list of icons 
# just type get_icon_names in your terminal.
#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(icons_test)

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="false"
DISABLE_UPDATE_PROMPT="false"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  aws 
  common-aliases 
  colorize
  docker 
  fzf 
  gcloud 
  git 
  gitfast 
  git-extras 
  history 
  iterm2
  jira
  oc 
  macos 
  pip
  python
  kubectl 
  kube-ps1 
  terraform 
  tmux 
  vagrant
  vscode
)


# User configuration
export PATH="/usr/local/bin:/opt/local/sbin:$HOME/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:~/src/go/bin:/usr/local/bin:/sw/bin:/usr/local/git/bin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

export JAVA_HOME=/usr/local/opt/openjdk
PATH=~/bin:/usr/local/opt/openjdk/jre/bin:$PATH:/usr/local/bin:/sw/bin:/usr/local/git/bin

# For mongodb
PATH=$PATH:$HOME/src/mongodb/mongodb-osx-x86_64-2.2.0/bin
#alias cd=pushd
#alias cdp=popd
alias ll='ls -la'
set -o vi

#Miami ISO stuff
alias m1p='ssh -D 1080 chirsch@161.69.46.16'
alias chrom='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --proxy-server="socks5://localhost:1080"'

# MacPorts Installer addition on 2014-04-30_at_17:32:58: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

# For packer
export PATH=~/Downloads/packer:$PATH

# For Go
export GOPATH="$HOME/src/go/"
#export GOROOT=/usr/local/opt/go/libexec

# fshow - git commit browser
fshow() {
  git log --graph --color=always \
      --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
  fzf --ansi --no-sort --reverse --tiebreak=index --bind=ctrl-s:toggle-sort \
      --bind "ctrl-m:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
                {}
FZF-EOF"
}

function kube-toggle() {
  if (( ${+POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND} )); then
    unset POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND
  else
    POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc|istioctl|kogito'
  fi
  p10k reload
  if zle; then
    zle push-input
    zle accept-line
  fi
}

# From Ben
# Quickly work with DDC environments
ddc() {
  echo "entering $1"
  cd ~/src/$DDC_SITE/docker/ddc-$1/
  eval "$(<env.sh)"
  cd -
}

alias d="docker"
# Docker Linter https://github.com/goodwithtech/dockle
alias dl="dockle"
alias g='git'
# https://hub.github.com/
# Makes git github compatible
alias h=hub
alias k="kubectl"
alias ke='kubectl get events --sort-by="{.lastTimestamp}"'
alias ks="kubens"
alias kx="kubectx"
alias t="docker inspect -f '{{.Status.ContainerStatus.ContainerID}}' "
alias ga="git add -p"
alias rs='rsync -av --progress'
alias ta='terraform apply'
alias tp='terraform plan'
alias cat="bat"
#alias bat="batcat"
alias cssh="i2cssh"
alias glog=fshow
#alias htop=glances
alias hackthegibson="docker ps -f name='^ucp-'"
# Show wide view of PS
alias psw="ps -eafwww"
alias scripts="cd $HOME/src/$DDC_SITE/des/des-scripts/scripts"
# For SSH tunneling
alias tunnel="sshuttle --dns -r $USER@$JUMPHOST 0/0"


# Start/Stop indexing on all volumes
alias spotlightoff='sudo mdutil -a -i off'
alias spotlighton='sudo mdutil -a -i on'

# load/unload indexing on all volumes
alias spotlightunload='sudo launchctl unload -w \
	 /System/Library/LaunchDaemons/com.apple.metadata.mds.plist'
alias spotlightload='sudo launchctl load -w \
	 /System/Library/LaunchDaemons/com.apple.metadata.mds.plist'

#alias vi='/usr/local/bin/vim'
# To get ctrl-r history search
bindkey "^R" history-incremental-search-backward

# use esc-v to edit the vim command line IN vim
bindkey -M vicmd v edit-command-line




#alias jobs='print "Remember %n to fg!\n";jobs'

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
#PS1="%{%f%b%k%}$(build_prompt) 🐓💩🔜 "

export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh



# Needed so that pgp prompt doesn't try for GUI
export GPG_TTY=$(tty)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Source the dotconfig aliases file AND overwrite that with any local aliases
[ -f ~/.config/aliases ] && source ~/.config/aliases
[ -f ~/.aliases ] && source ~/.aliases

# Source the local site file to setup vars depending on which computer/customer/environment we're in
[ -f ~/.site ] && source ~/.site

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

eval "$(pyenv init -)"

export LDFLAGS="-L/usr/local/opt/zlib/lib -L/usr/local/opt/sqlite/lib"
export CPPFLAGS="-I/usr/local/opt/zlib/include -I/usr/local/opt/sqlite/include"

export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export WORKON_HOME=~/.virtualenvs
export VIRTUALENVWRAPPER_VIRTUALENV=~/.pyenv/versions/3.7.3/bin/virtualenv

